spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aichao-liu/spring-cloud-config/
          search-paths: config
          default-label: master
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/