eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8004
feign:
  hystrix:
    #熔断器配置，默认为false
    enabled: true
spring:
  application:
    name: consumer-feign